apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster

containerdConfigPatches:
- |
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
    endpoint = ["http://registry:5000"]

networking:
  apiServerAddress: 172.17.0.1
  ipFamily: ipv4
  disableDefaultCNI: true   # do not install kindnet
nodes:
- role: control-plane
- role: worker
- role: worker
